export const mantraCases = [
  ["om namah shivaya", "ॐ नमः शिवाय"],
  ["om namh shivay", "ॐ नमः शिवाय"],
  ["om namah shivay", "ॐ नमः शिवाय"],
  ["om namo shivaya", "ॐ नमो शिवाय"],
  ["om tryambakam yajamahe", "ॐ त्र्यम्बकं यजामहे"],
  ["om tryambakam yajamahey", "ॐ त्र्यम्बकं यजामहे"],
  ["mrityor mukshiya maamritat", "मृत्योर्मुक्षीय मामृतात्"],
  ["maha mrityunjaya mantra", "महामृत्युंजय मंत्र"],
  ["har har mahadev", "हर हर महादेव"],
  ["om rudraya namah", "ॐ रुद्राय नमः"],
  ["om shankaraya namah", "ॐ शंकराय नमः"],
  ["om mahadevaya namah", "ॐ महादेवाय नमः"],
  ["om bhavaya namah", "ॐ भवाय नमः"],
  ["om sharvaya namah", "ॐ शर्वाय नमः"],
  ["om pashupataye namah", "ॐ पशुपतये नमः"],
  ["om nilakanthaya namah", "ॐ नीलकण्ठाय नमः"],
  ["om gangadharaya namah", "ॐ गंगाधराय नमः"],
  ["om kapardine namah", "ॐ कपर्दिने नमः"],
  ["om vishwanathaya namah", "ॐ विश्वनाथाय नमः"],
  ["om kedarnathaya namah", "ॐ केदारनाथाय नमः"],
  ["om namo narayanaya", "ॐ नमो नारायणाय"],
  ["om namo narayan", "ॐ नमो नारायण"],
  ["om vishnave namah", "ॐ विष्णवे नमः"],
  ["om narayanaya namah", "ॐ नारायणाय नमः"],
  ["om vasudevaya namah", "ॐ वासुदेवाय नमः"],
  ["om namo bhagavate vasudevaya", "ॐ नमो भगवते वासुदेवाय"],
  ["om namo bhagwate vasudevay", "ॐ नमो भगवते वासुदेवाय"],
  ["om achyutaya namah", "ॐ अच्युताय नमः"],
  ["om anantaya namah", "ॐ अनन्ताय नमः"],
  ["om govindaya namah", "ॐ गोविन्दाय नमः"],
  ["om madhavaya namah", "ॐ माधवाय नमः"],
  ["om keshavaya namah", "ॐ केशवाय नमः"],
  ["om hrishikeshaya namah", "ॐ हृषीकेशाय नमः"],
  ["om damodaraya namah", "ॐ दामोदराय नमः"],
  ["om krishnaya namah", "ॐ कृष्णाय नमः"],
  ["om shri krishnaya namah", "ॐ श्री कृष्णाय नमः"],
  ["hare krishna hare krishna", "हरे कृष्ण हरे कृष्ण"],
  ["krishna krishna hare hare", "कृष्ण कृष्ण हरे हरे"],
  ["hare rama hare rama", "हरे राम हरे राम"],
  ["rama rama hare hare", "राम राम हरे हरे"],
  ["hare krishna hare rama", "हरे कृष्ण हरे राम"],
  ["hare ram hare krishna", "हरे राम हरे कृष्ण"],
  ["radhe radhe", "राधे राधे"],
  ["radha krishna", "राधा कृष्ण"],
  ["radhe krishna radhe krishna", "राधे कृष्ण राधे कृष्ण"],
  ["om radhikayai namah", "ॐ राधिकायै नमः"],
  ["om ramaya namah", "ॐ रामाय नमः"],
  ["om ram ramaya namah", "ॐ राम रामाय नमः"],
  ["shri ram jai ram jai jai ram", "श्री राम जय राम जय जय राम"],
  ["shree ram jai ram jai jai ram", "श्री राम जय राम जय जय राम"],
  ["ram ram ram ram", "राम राम राम राम"],
  ["jai shri ram", "जय श्री राम"],
  ["jai shree ram", "जय श्री राम"],
  ["sita ram sita ram", "सीता राम सीता राम"],
  ["om hanumate namah", "ॐ हनुमते नमः"],
  ["om namah hanumate", "ॐ नमः हनुमते"],
  ["om shri hanumate namah", "ॐ श्री हनुमते नमः"],
  ["om anjaneyaya namah", "ॐ अञ्जनेयाय नमः"],
  ["om anjaneya namah", "ॐ अञ्जनेय नमः"],
  ["om marutaye namah", "ॐ मारुतये नमः"],
  ["jai hanuman", "जय हनुमान"],
  ["jai bajrangbali", "जय बजरंगबली"],
  ["sankat mochan hanuman", "संकट मोचन हनुमान"],
  ["om gan ganapataye namah", "ॐ गं गणपतये नमः"],
  ["om gam ganapataye namah", "ॐ गं गणपतये नमः"],
  ["om ganeshaya namah", "ॐ गणेशाय नमः"],
  ["om shri ganeshaya namah", "ॐ श्री गणेशाय नमः"],
  ["om shree ganeshaya namah", "ॐ श्री गणेशाय नमः"],
  ["om vakratundaya hum", "ॐ वक्रतुण्डाय हुं"],
  ["vakratunda mahakaya", "वक्रतुण्ड महाकाय"],
  ["mangalam bhagavan vishnu", "मंगलं भगवान विष्णु"],
  ["mangalam garudadhwaja", "मंगलं गरुडध्वज"],
  ["mangalam pundarikaksha", "मंगलं पुण्डरीकाक्ष"],
  ["mangalaya tano hari", "मंगलाय तनो हरि"],
  ["om durgaye namah", "ॐ दुर्गायै नमः"],
  ["om shri durgaye namah", "ॐ श्री दुर्गायै नमः"],
  ["om dum durgaye namah", "ॐ दुं दुर्गायै नमः"],
  ["om mahalakshmyai namah", "ॐ महालक्ष्म्यै नमः"],
  ["om shri mahalakshmyai namah", "ॐ श्री महालक्ष्म्यै नमः"],
  ["om lakshmyai namah", "ॐ लक्ष्म्यै नमः"],
  ["om saraswatyai namah", "ॐ सरस्वत्यै नमः"],
  ["om aim saraswatyai namah", "ॐ ऐं सरस्वत्यै नमः"],
  ["om shri saraswatyai namah", "ॐ श्री सरस्वत्यै नमः"],
  ["om parvatyai namah", "ॐ पार्वत्यै नमः"],
  ["om gauri namah", "ॐ गौरी नमः"],
  ["om gauryai namah", "ॐ गौर्यै नमः"],
  ["om kalikayai namah", "ॐ कालिकायै नमः"],
  ["om mahakalikayai namah", "ॐ महाकालिकायै नमः"],
  ["om aim hreem kleem chamundaye vichche", "ॐ ऐं ह्रीं क्लीं चामुण्डायै विच्चे"],
  ["om aim hrim klim chamundaye vichche", "ॐ ऐं ह्रीं क्लीं चामुण्डायै विच्चे"],
  ["ya devi sarva bhuteshu", "या देवी सर्वभूतेषु"],
  ["sarva mangala mangalye", "सर्वमंगल मांगल्ये"],
  ["sharanagata dinarta paritrana parayane", "शरणागत दीनार्त परित्राण परायणे"],
  ["sarvasyarti hare devi", "सर्वस्यार्तिहरे देवि"],
  ["narayani namostute", "नारायणि नमोऽस्तुते"],
  ["om aim hreem shreem namah", "ॐ ऐं ह्रीं श्रीं नमः"],
  ["om shreem maha lakshmyai namah", "ॐ श्रीं महालक्ष्म्यै नमः"],
  ["om hreem namah", "ॐ ह्रीं नमः"],
  ["om kreem kalikayai namah", "ॐ क्रीं कालिकायै नमः"],
  ["om dum durgayei namah", "ॐ दुं दुर्गायै नमः"],
  ["gayatri mantra", "गायत्री मंत्र"],
  ["om bhur bhuvah svah", "ॐ भूर्भुवः स्वः"],
  ["tat savitur varenyam", "तत्सवितुर्वरेण्यं"],
  ["bhargo devasya dhimahi", "भर्गो देवस्य धीमहि"],
  ["dhiyo yo nah prachodayat", "धियो यो नः प्रचोदयात्"],
  ["om bhur bhuvah swaha", "ॐ भूर्भुवः स्वः"],
  ["om adityaya namah", "ॐ आदित्याय नमः"],
  ["om somaya namah", "ॐ सोमाय नमः"],
  ["om angarakaya namah", "ॐ अंगारकाय नमः"],
  ["om budhaya namah", "ॐ बुधाय नमः"],
  ["om brihaspataye namah", "ॐ बृहस्पतये नमः"],
  ["om shukraya namah", "ॐ शुक्राय नमः"],
  ["om shanaischaraya namah", "ॐ शनैश्चराय नमः"],
  ["om rahave namah", "ॐ राहवे नमः"],
  ["om ketave namah", "ॐ केतवे नमः"],
  ["navagraha mantra", "नवग्रह मंत्र"],
  ["surya dev mantra", "सूर्य देव मंत्र"],
  ["om suryaya namah", "ॐ सूर्याय नमः"],
  ["om savitre namah", "ॐ सवित्रे नमः"],
  ["om shanti shanti shanti", "ॐ शान्तिः शान्तिः शान्तिः"],
  ["sarve bhavantu sukhinah", "सर्वे भवन्तु सुखिनः"],
  ["sarve santu niramayah", "सर्वे सन्तु निरामयाः"],
  ["sarve bhadrani pashyantu", "सर्वे भद्राणि पश्यन्तु"],
  ["ma kashchid dukha bhag bhavet", "मा कश्चिद्दुःखभाग्भवेत्"],
  ["lokah samastah sukhino bhavantu", "लोकाः समस्ताः सुखिनो भवन्तु"],
  ["asato ma sadgamaya", "असतो मा सद्गमय"],
  ["tamaso ma jyotirgamaya", "तमसो मा ज्योतिर्गमय"],
  ["mrityor ma amritam gamaya", "मृत्योर्मा अमृतं गमय"],
  ["om purnamadah purnamidam", "ॐ पूर्णमदः पूर्णमिदम्"],
  ["om saha navavatu", "ॐ सह नाववतु"],
  ["saha nau bhunaktu", "सह नौ भुनक्तु"],
  ["saha viryam karavavahai", "सह वीर्यं करवावहै"],
  ["tejasvinavadhitamastu", "तेजस्विनावधीतमस्तु"],
  ["ma vidvishavahai", "मा विद्विषावहै"],
  ["om agne naya supatha", "ॐ अग्ने नय सुपथा"],
  ["om asato ma sadgamaya", "ॐ असतो मा सद्गमय"],
  ["om dyauh shantih", "ॐ द्यौः शान्तिः"],
  ["antariksham shantih", "अन्तरिक्षं शान्तिः"],
  ["prithivi shantih", "पृथिवी शान्तिः"],
  ["apah shantih", "आपः शान्तिः"],
  ["oshadhayah shantih", "ओषधयः शान्तिः"],
  ["vanaspatayah shantih", "वनस्पतयः शान्तिः"],
  ["vishvedevah shantih", "विश्वेदेवाः शान्तिः"],
  ["brahma shantih", "ब्रह्म शान्तिः"],
  ["sarvam shantih", "सर्वं शान्तिः"],
  ["shantireva shantih", "शान्तिरेव शान्तिः"],
  ["om shanti", "ॐ शान्ति"],
  ["om namah", "ॐ नमः"],
  ["om tat sat", "ॐ तत् सत्"],
];
